<?php

namespace Fos\MainBundle\Repository;

/**
 * companiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class companiesRepository extends \Doctrine\ORM\EntityRepository
{
}
