<?php

namespace Fos\MainBundle\Repository;

/**
 * sasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sasRepository extends \Doctrine\ORM\EntityRepository
{
}
